name: workspace deployment

on:
    push:
        branches: [ workspace_publish ]
    workflow_dispatch:
    
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - 
          uses: Azure/Synapse-workspace-deployment@V1.8.0
          with:
            TargetWorkspaceName: 'synapse-met-cicd-uat'
            TemplateFile: './synapse-met-cicd-dev/TemplateForWorkspace.json'
            ParametersFile: './synapse-met-cicd-dev/TemplateParametersForWorkspace.json'
            environment: 'Azure Public'
            resourceGroup: 'aaaaaatest'
            clientId: ${{secrets.CLIENTID}}
            clientSecret:  ${{secrets.CLIENTSECRET}}
            subscriptionId: ${{secrets.SUBSCIPTIONID}}
            tenantId: ${{secrets.TENANTID}}
            DeleteArtifactsNotInTemplate: 'false'
        
