name: workspace deployment

on:
    push:
        branches: [ workspace_publish ]
    workflow_dispatch:
    
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - name: Check out repo
          uses: actions/checkout@v2
          with: 
            ref: workspace_publish

        - name: Azure Login
          uses: Azure/login@v1.4.6
          with:
            # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
            creds: ${{secrets.AZURE_CREDENTIALS}}
            # ClientId of the Azure Service principal created.
            #client-id: ${{secrets.CLIENTID}}
            # TenantId of the Azure Service principal created.
            #tenant-id:  ${{secrets.TENANTID}}
            # Azure subscriptionId
            #subscription-id: ${{secrets.SUBSCRIPTIONID}}
         
        - name: Deploy Synapse workspace
          uses: azure/synapse-workspace-deployment@release-1.0
          with:
            TargetWorkspaceName: 'synapse-met-cicd-uat'
            TemplateFile: './synapse-met-cicd-dev/TemplateForWorkspace.json'
            ParametersFile: './synapse-met-cicd-dev/TemplateParametersForWorkspace.json'
            environment: 'Azure Public'
            resourceGroup: 'aaaaaatest'
            clientId: ${{secrets.CLIENTID2}}
            clientSecret:  ${{secrets.CLIENTSECRET2}}
            subscriptionId: ${{secrets.SUBSCIPTIONID}}
            tenantId: ${{secrets.TENANTID}}
            DeleteArtifactsNotInTemplate: 'false'
        
